watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"
bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["komorebi_workspaces", "active_window"]
      center: ["clock"]
      right: ["media", "weather", "memory", "volume", "power_menu"]
widgets:
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "\uf001 {title}"
        label_alt: "\uf001 {artist}"
        hide_empty: true
        max_field_size:
          label: 30
          label_alt: 30
        show_thumbnail: false
        controls_hide: true
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%I:%M %p}"
        timezones: []
        calendar:
          alignment: "center"
  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
          label_offline: "\ue654 Offline"
          label_workspace_btn: "\udc3d"
          label_workspace_populated_btn: "\udb81\udc3e"
          hide_empty_workspaces: false
          hide_if_offline: false
          animation: true
  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {temp}"
        api_key: 'fbe53750f5524f9bafb201037252704'
        update_interval: 600
        hide_decimal: true
        location: 'Rio De Janeiro'
        callbacks:
          on_left: "do_nothing"
        icons: 
          sunnyDay: "\ue30d"
          clearNight: "\ue32b"
          cloudyDay: "\udb81\udd99"
          cloudyNight: "\ue311"
          rainyDay: "\udb81\ude7e"
          rainyNight: "\udb81\ude7e"
          snowyIcyDay: "\udb81\udd98"
          snowyIcyNight: "\udb81\udd98"
          blizzard: "\uebaa"
          default: "\uebaa"
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "{volume}"
        volume_icons:
          - "\ueee8"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "toggle_mute"
          on_left: "do_nothing"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250
        button_row: 5
        buttons:
          signout: ["\udb80\udf43", "Sign out"]
          shutdown: ["\uf011", "Shut Down"]
          restart: ["\uead2", "Restart"]
          hibernate: ["\uf28e", "Hibernate"]
          cancel: ["\udb81\udf3a", "Cancel"]
  active_window:
      type: "yasb.active_window.ActiveWindowWidget"
      options:
        label: "{win[title]}"
        label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
        label_no_window: ""
        label_icon: false
        max_length: 64
        max_length_ellipsis: "..."
        monitor_exclusive: true
  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uf4bc</span> {virtual_mem_used}"
        update_interval: 7500
        callbacks:
          on_left: 'do_nothing'
        memory_thresholds:
          low: 25
          medium: 50
          high: 90