watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    widgets:
      left: ["komorebi_workspaces"]
      center: ["media"]
      right: ["cpu", "separator", "memory", "separator", "volume", "separator", "clock"]
widgets:
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "cpu {info[percent][total]}%"
      label_alt: 
      update_interval: 7500
      callbacks:
        on_left: "do_nothing"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "mem {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 7500
      callbacks:
        on_left: "do_nothing"
  separator:
    type: "yasb.custom.CustomWidget"
    options:
      label: "::"
      label_alt: "::"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "\uf001 {title}"
      label_alt: "\uf001 {artist}"
      hide_empty: true
      max_field_size:
        label: 100
        label_alt: 100
      show_thumbnail: false
      controls_hide: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "time {%Y-%m-%d %H:%M:%S}"
      label_alt: "time {%Y-%m-%d %H:%M:%S}"
      timezones: []
      callbacks:
        on_left: "do_nothing"
        on_right: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: " \ue654 Offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      label_default_name: "{index}"
      hide_empty_workspaces: false
      hide_if_offline: false
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "vol {level}"
      callbacks:
        on_right: "toggle_mute"
        on_left: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: false
      label_icon_size: 14
      max_length: 60
      max_length_ellipsis: "..."
      monitor_exclusive: false
      callbacks:
        on_left: "do_nothing"