"$schema" = 'https://starship.rs/config-schema.json'

format = "$username@$hostname $directory % "
add_newline = false

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[directory]
truncation_length = 999
truncate_to_repo = false
read_only = ""
use_os_path_sep = true
style = "white"
format = "$path"
