"$schema" = 'https://starship.rs/config-schema.json'

format = "$directory \\$ "

add_newline = false

[directory]
truncation_length = 999
truncate_to_repo = false
read_only = ""
use_os_path_sep = true
style = 'blue bold'
format = '[$path]($style)'
