watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 20
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["komorebi_workspaces", "komorebi_active_layout", "active_window"]
      right: ["media", "memory", "separator", "volume", "separator", "calendar", "separator", "clock"]
widgets:
  separator:
    type: "yasb.custom.CustomWidget"
    options:
      label: "|"
      label_alt: "|"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "cpu {info[percent][total]}%"
      update_interval: 2000
      callbacks:
        on_left: "do_nothing"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 2000
      callbacks:
        on_left: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: " \ue654 offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      hide_empty_workspaces: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8 "  # Icon for muted
        - "\uf026 "  # Icon for 0-10% volume
        - "\uf027 "  # Icon for 11-30% volume
        - "\uf027 "  # Icon for 31-60% volume
        - "\uf028 "  # Icon for 61-100% volume
      callbacks:
        on_left: "do_nothing"
        on_right: "toggle_mute"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\uf017 {%I:%M %p} \uec03"
      label_alt: "\uf017 {%I:%M %p} \uec03"
      locale: ""
      update_interval: 1000
      timezones: []
      callbacks:
        on_left: "do_nothing"
        on_right: "do_nothing"
        on_middle: "do_nothing"
  calendar:
    type: "yasb.clock.ClockWidget"
    options:
      label: "\udb80\udcee {%a. %d/%m}"
      label_alt: "\udb80\udcee {%a. %d/%m}"
      callbacks:
        on_left: "do_nothing"
        on_right: "do_nothing"
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_middle: 'toggle_layout_menu'
        on_left: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: true
        round_corners: false
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: " \uf001 {title} |"
      label_alt: " \uf001 {artist} |"
      hide_empty: true
      callbacks:
        on_left: "toggle_label"
        on_right: "do_nothing"
      max_field_size:
        label: 50
        label_alt: 50
      show_thumbnail: false
      controls_hide: true
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: false
      label_icon_size: 16
      max_length: 100
      max_length_ellipsis: "..."
      monitor_exclusive: true
