watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start --whkd"
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 20
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left: ["komorebi_workspaces"]
      center: ["media"]
      right: ["cpu", "separator", "memory", "separator", "volume", "separator", "clock"]
widgets:
  separator:
    type: "yasb.custom.CustomWidget"
    options:
      label: "|"
      label_alt: "|"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "cpu {info[percent][total]}%"
      update_interval: 7500
      callbacks:
        on_left: "do_nothing"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "mem {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 7500
      callbacks:
        on_left: "do_nothing"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "time {%Y-%m-%d %H:%M:%S}"
      timezones: []
      callbacks:
        on_left: "do_nothing"
        on_right: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: " \ue654 offline"
      label_workspace_btn: "{index}"
      label_workspace_active_btn: "{index}"
      label_workspace_populated_btn: "{index}"
      hide_empty_workspaces: true
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "vol {level}"
      callbacks:
        on_right: "toggle_mute"
        on_left: "do_nothing"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} \uf001 {title}"
      hide_empty: true
      max_field_size:
        label: 100
      show_thumbnail: false
      controls_hide: true
      callbacks:
        on_left: "do_nothing"
